## Definição do *dataset*

O *dataset utilizado será o "TOWARDS LIMB POSITION INVARIANT MYOELECTRIC PATTERN RECOGNITION USING TIME-DEPENDENT SPECTRAL FEATURES" [1]. Maiores informações podem ser vistas no site: https://www.rami-khushaba.com/electromyogram-emg-repository.html

De acordo com a figura seguinte, neste *dataset* existem 5 posições e 8 movimentos. Algumas questões de projetos foram levadas em consideração:
1. A primeira posição (P1) possui 40.000 *samples* e todas as outras possuem 20.000 *samples*. Desta forma, a posição 1 foi **excluída** do experimento de teste;
2. Cada posição possui 5 tentativas. Desta forma, será utilizada todas as tentativas do mesmo movimento como uma soma total de *samples* (todas as tentativas serão concatenadas);
3. Como este experimento resultará em 4 posições e 8 movimentos, será considerado primeiramente um experimento com 32 classes (4 * 8) e um segundo experimento com 8 classes (somando/dispresando as posições do braço).

[1] R. N. Khushaba, Maen Takruri, Jaime Valls Miro, and Sarath Kodagoda, "Towards limb position invariant myoelectric pattern recognition using time-dependent spectral features", Neural Networks, vol. 55, pp. 42-58, 2014. https://doi.org/10.1016/j.neunet.2014.03.010

### Separação das classes

In [30]:
from glob import glob

# exclusão dos arquivos com "Pos1" no nome
arquivos = glob("datasets/EMG_data/Pos[2-5]*.txt")
# índices para as 32 classes considerando as posições de 2 à 5
cl32 = {
    "Pos2_HandOpen": list(), "Pos3_HandOpen": list(), "Pos4_HandOpen": list(), "Pos5_HandOpen": list(),
    "Pos2_HandRest": list(), "Pos3_HandRest": list(), "Pos4_HandRest": list(), "Pos5_HandRest": list(),
    "Pos2_ObjectGrip": list(), "Pos3_ObjectGrip": list(), "Pos4_ObjectGrip": list(), "Pos5_ObjectGrip": list(),
    "Pos2_PichGrip": list(), "Pos3_PichGrip": list(), "Pos4_PichGrip": list(), "Pos5_PichGrip": list(),
    "Pos2_WristExten": list(), "Pos3_WristExten": list(), "Pos4_WristExten": list(), "Pos5_WristExten": list(),
    "Pos2_WristFlex": list(), "Pos3_WristFlex": list(), "Pos4_WristFlex": list(), "Pos5_WristFlex": list(),
    "Pos2_WristPron": list(), "Pos3_WristPron": list(), "Pos4_WristPron": list(), "Pos5_WristPron": list(),
    "Pos2_WristSupi": list(), "Pos3_WristSupi": list(), "Pos4_WristSupi": list(), "Pos5_WristSupi": list(),
}
# índices para as 8 classes desconsiderando as posições de 2 à 5
cl08 = {
    "HandOpen": list(),
    "HandRest": list(),
    "ObjectGrip": list(),
    "PichGrip": list(),
    "WristExten": list(),
    "WristFlex": list(),
    "WristPron": list(),
    "WristSupi": list(),
}

## Carregamento do *dataset*

Neste trecho de código, todos as amostras serão dividas entre os conjuntos de calsses específicas

In [31]:
import re

for arquivo in arquivos:
    trial_file = open(arquivo)
    nome = trial_file.name.split('/')[-1].split('.')[0]
    trial = list()
    for linha in trial_file.readlines():
        # foi necessário substituir os números "int" por "float"
        linha = re.sub(r"(?<=\ )(\d)(?=\ )", r"\1.0", linha)
        # casamento da linha com 7 pontos (1 para cada eletrodo)
        sample = [float(s) for s in re.findall(r"\-?\d\.\d+", linha)]
        trial.append(sample)
    cl08["{}".format(nome[5:-3])].append(trial)
    cl32["Pos{}{}".format(nome[3], nome[4:-3])].append(trial)

Agora será realizado a divisão dos dados e suas respectivas classes em sequência, formando dados em `numpy.array` para X1 (dados EMG das 8 classes), y1 (*labels* das 8 classes), X2 (dados EMG das 32 classes), y2 (*labels* das 32 classes)

In [32]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

X1 = np.array(list(cl08.values()))
X2 = np.array(list(cl32.values()))
# transformando labels categóricos em numéricos
le = LabelEncoder()
y1 = np.array(le.fit_transform(list(cl08.keys())))
y2 = np.array(le.fit_transform(list(cl32.keys())))
# shape: [8 classes, 24 trials, 20000 samples, 7 eletrodos]
print(X1.shape)
# shape: [32 classes, 6 trials, 20000 samples, 7 eletrodos]
print(X2.shape)
print(y1)
print(y2)

(8, 24, 20000, 7)
(32, 6, 20000, 7)
[0 1 2 3 4 5 6 7]
[ 0  8 16 24  1  9 17 25  2 10 18 26  3 11 19 27  4 12 20 28  5 13 21 29
  6 14 22 30  7 15 23 31]


É necessário inverter os eixos dos "samples" e dos "eletrodos"

In [33]:
X1 = X1.swapaxes(2, 3)
X2 = X2.swapaxes(2, 3)
print(X1.shape)
print(X2.shape)

(8, 24, 7, 20000)
(32, 6, 7, 20000)


## Extração de características

Vamos agora aplicar a extração de características dos sinais. A titulo de exemplificação, daqui pra frente iremos trabalhar apenas com os dados com 8 classes (`X1` e `y1`).

Serão extraídas 4 características de cada eletrodo como exemplo. 2 no domímio do tempo (`VAR` e `RMS`) e 2 no domínio da frequência (`FMD` e `MMDF`):
* `Variance of EMG (VAR)`: 
    > $\frac{1}{N-1}\sum_{i=1}^{N}x_i^2$
* `Root Mean Square (RMS)`:
    > $\sqrt{\frac{1}{N-1}\sum_{i=1}^{N}|x_i|^2}$
* `Frequency Median (FMD)`:
    > $\frac{1}{2}\sum_{i=1}^{M}PSD$
* `Modified Median Frequency (MMDF)`:
    > $\frac{1}{2}\sum_{i=1}^{M}A_j$

Para a transformação dos dados no domínio da frequência, será utilizado a biblioteca `librosa`.

No final, o vetor de características estará organizado da seguinte forma:

| ID sample | VAR1 | RMS1 | FMD1 | MMDF1 | VAR2 | RMS2 | FMD2 | MMDF2 | ... | MMDF8 | Classe |
|:---------:|:----:|:----:|:----:|:-----:|------|------|------|-------|-----|-------|:------:|
|     1     |  v1  |  v1  |  v1  |   v1  | v1   | v1   | v1   | v1    | v1  | v1    |    0   |
|     2     |  v2  |  v2  |  v2  |   v2  | v2   | v2   | v2   | v2    | v2  | v2    |    0   |
|    ...    |  ... |  ... |  ... |  ...  | ...  | ...  | ...  | ...   | ... | ...   |   ...  |
|     N     |  vN  |  vN  |  vN  |   vN  | vN   | vN   | vN   | vN    | vN  | vN    |    7   |

### Segmentação dos dados

In [64]:
print(X1.shape)
# definição do salto e do tamanho do segmento (segmento - salto = sobreposição)
salto = 470
segmento = 1024
n_win = int((X1.shape[-1] - segmento) / salto) + 1
ids = np.arange(n_win) * salto
x = np.array([X1[:,:,:,k:(k + segmento)] for k in ids]).transpose(1, 2, 3, 0, 4)
print(x.shape)

(8, 24, 7, 20000)
(8, 24, 7, 41, 1024)


### Implementação das características no domínio do tempo

In [90]:
# VAR
var = np.sum(x ** 2, axis=-1) / (np.prod(x.shape[:-1]) - 1)
print(var.shape)
# RMS
rms = np.sqrt(np.sum(np.abs(x) ** 2, axis=-1) / (np.prod(x.shape[:-1]) - 1))
print(rms.shape)

(8, 24, 7, 41)
(8, 24, 7, 41)


#### Transformação para o domínio da frequência

In [91]:
# from librosa import stft

# aplicando stft no último eixo de X1 (3), com janela de 2048 e sobreposição de 512
# w = np.apply_along_axis(stft, 3, X1, n_fft=2048, hop_length=512)
# w = np.swapaxes(w, 3, 4)

from scipy.signal import stft

print(X1.shape)
_, _, w = stft(X1, fs=4000, nperseg=1024, noverlap=512)
w = np.swapaxes(w, 3, 4)
print(w.shape)

(8, 24, 7, 20000)
(8, 24, 7, 41, 513)


### Implementação das características no domínio da frequência

In [92]:
# definição da função PSD para o sinal no domínio da frequência
def PSD(x):
    return np.sqrt(np.abs(x))

# FMD
fmd = np.sum(PSD(w), axis=-1) / 2
print(fmd.shape)
# MMDF
mmdf = np.sum(np.abs(w), axis=-1) / 2
print(mmdf.shape)

(8, 24, 7, 41)
(8, 24, 7, 41)


Agora é necessesário realizar algumas mudanças na disposição dos dados para que o vetor de características fique da forma como foi mencionado anteriormente.

O vetor de características deve ser bidimensional (samples, features) para entrar como parâmetro de dados no classificador.

#### Criação do vetor de características

In [93]:
features = list()
for feature in (var, rms, fmd, mmdf):
    feature = feature.transpose(0, 1, 3, 2)
    feature = feature.reshape(8 * 24 * 41, 7)
    print('Feature: {}'.format(feature), feature.shape)
    features.append(feature)

X = np.concatenate(features, axis=-1)
X.shape

Feature: [[3.32672701e-05 2.18137582e-05 3.68548167e-03 ... 5.22328989e-03
  1.24049636e-04 3.18158393e-05]
 [3.18581240e-05 1.66211906e-05 2.52739411e-03 ... 6.29495037e-03
  1.18988996e-04 2.41488434e-05]
 [2.48037266e-05 1.27430402e-05 1.75369706e-03 ... 7.61754319e-03
  1.21221466e-04 2.48292863e-05]
 ...
 [2.89127766e-05 1.40552334e-04 6.04504845e-03 ... 1.73190118e-03
  4.51963502e-04 8.46710804e-05]
 [3.10607639e-05 1.71067574e-04 7.03700296e-03 ... 1.77984168e-03
  4.58224891e-04 8.56156497e-05]
 [2.18737747e-05 1.46657270e-04 8.24495656e-03 ... 1.92052715e-03
  6.70711832e-05 1.90495150e-05]] (7872, 7)
Feature: [[0.00576778 0.00467052 0.06070817 ... 0.07227233 0.01113776 0.00564055]
 [0.0056443  0.00407691 0.05027319 ... 0.07934072 0.01090821 0.00491415]
 [0.00498033 0.00356974 0.04187717 ... 0.08727854 0.01101006 0.0049829 ]
 ...
 [0.00537706 0.01185548 0.07774991 ... 0.04161612 0.02125943 0.00920169]
 [0.00557322 0.01307928 0.08388685 ... 0.04218817 0.02140619 0.00925287]
 [

(7872, 28)

#### Criação do vetor de labels

In [102]:
y = np.array([[str(i)] * int(X.shape[0] / 8) for i in range(8)])
y = y.reshape(y.shape[0] * y.shape[1])
y.shape

(7872,)

Agora é realizado a parte de classificação.

O classificador `SVM` da biblioteca `scikit-learn` possui diversos modelos de classificação utilizando máquinas de vetores de suporte. As mais comuns são a `SVC` para aplicar modelos de classificação e a `SVR` para modelos de regressão linear. Para este caso, vamos utilizar o `SVC`.

### Aplicação do classificador SVM

In [113]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

# dividindo as porções de dados em treino e teste (70 e 30% respectivamente)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True)

# o trabalho das diferentes parametrizações ficam a cargo dos alunos
clf = SVC(gamma='auto')
clf.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

#### Criando a rotina simples de teste

In [117]:
res = clf.predict(X_test)
tot_hit = sum([1 for i in range(len(res)) if res[i] == y_test[i]])
print('Acurácia: {:.2f}%'.format(tot_hit / X_test.shape[0] * 100))

Acurácia: 94.71%
